language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: bvdrucker@gmail.com
  api_key:
    secure: hql1uls4qo8ovmv4+SSeEI9y+BicN25ENm2bqLjtOZ/GKpfuEczn1DFWQ2CF6Rs0C0IHKKcyuppcnJZX07cZ/Mp5dBAAxDcsef7QsKGZ2kijgCK900hSdCuLLwqTYA+aTU71Luv9nqf0Dh411HLEBjg2ArraFVHwzOlWaq+vVaQ=
  on:
    tags: true
    repo: bendrucker/karma-env
